### PR TITLE
imputation with ranger::ranger()

### PR DESCRIPTION
**Pull request by GregorDeCillia**
This is far from finised. Starting the PR so we have some place to exchange ideas about the RF imputations.

TODOs:
- [x] add glue functions to make this work with survey objects and so forth. Currently, only `randomForestImp_work()` is implemented and exported directly. This contradicts the naming conventions of VIM.
- [x] ~~use better defaults for `ranger::ranger()`. Factors are currently treated as integers AFAIK.~~ ¹
- [x] allow "median" for aggregation of trees for a more robust estimate
- [x] ~~allow a way to return the estimation of every tree?~~ ²
- [x] Add a `verbose` option that informs the user about which percentage of data could be used for training. This logic can also be used in `regressionImp`
- [x] Add a vignette for the new features
- [x] Add regression tests

@alexkowa what do you think about the naming of the function? IMO, `rangerImp()`, `rangerImpute()`, `randomForestImp()` and `randomForestImpute()` all sound good.

Also inviting @JohannesGuss to join the discussion for possible defaults and extensions.

¹: the `...` argument allows the user to specify details on how `ranger()` operates
²: It is unclear how the UX of this feature should be implemented. We might add support for this later but leave it open for now

### CODE REVIEW

**Comment by alexkowa** [comment]
How about we completely remove the survey object support?

**Comment by GregorDeCillia** [comment]
Not supporting survey objects seems fine to me. In this case, I could just rename the function and also omit the method dispatch (`UseMethod()`).

**Comment by alexkowa** [comment]
as for the naming: rangerImpute is probably my favourite, because it is more precise what we actually use...

**Comment by alexkowa** [comment]
Yes, probably we could do this for all imputation functions. I don't think anyone uses the survey object mehtods

**Comment by GregorDeCillia** [comment]
Ok, so I will omit survey support for this function and also disable it for other functions in the master branch after merging. In this case, I would suggest a major version bump soon since it introduces breaking changes to the package API

**Comment by GregorDeCillia** [comment]
@alexkowa I'm done with the TODOs

* special handling of regressors of type "factor" can be specified by the user with the `...` argument
* returning all trees seems like a fine feature, but I can't decide how the UX should look, so I won't add it for now

please let me know if there is anything that I missed. Otherwise, I think this branch is ready for merging.

**Comment by GregorDeCillia** [comment]
Actuall, I'll add some regression tests and a vignette to this branch prior to merging. The vignette will also cover `reressionImp()` since the interfaces are fairly similar.

**Pull request merged**
