### PR TITLE
remove support for survey.design objects

### PR DESCRIPTION
**Pull request by GregorDeCillia**
only implement the imputation functions for objects of type `data.frame` (and `data.table`) and drop support for `survey.design` objects.

- [x] remove method dispatch and only expose one function for each imputation method
- [x] properly test if `data.table` causes any issues
- [x] Make sure the documentation is in-line with these changes
- [x] do some typechecking and implement a special "deprication error" if an object of type `survey.design` is passed for `data`
- [x] (possibly) remove survey support also for the visualization functions and remove the package `methods` from the upstream dependencies
- [x] check if VIM has any downstream dependencies on CRAN which use the survey interface. @alexkowa or @matthias-da: do you know how to do that automatically? I know there is some package for reverse dependency checks on [r-lib](http://www.github.com/r-lib) ...

### CODE REVIEW

**Comment by GregorDeCillia** [comment]
There are currently 10 S3 methods left

https://github.com/statistikat/VIM/blob/367004169bef84afbd9665731b2fe0b1707ec7bb/NAMESPACE#L3-L12

I suggest we also remove `aggr.*()` and `prepare.*()` and reduce this to 
 the 4 `*.aggr()` methods.

**Comment by GregorDeCillia** [comment]
@alexkowa or @matthias-da can you run `revdepcheck::revdep_check()` for this branch to see if there are any issues with reverse dependencies? I can't get this to work at the moment.

**Comment by alexkowa** [comment]
revdepcheck is fine.
`
─ CHECK ────────────────────────────── 8 packages ──

✓ destiny 3.0.1                          ── E: 1     | W: 1     | N: 8    

✓ micemd 1.6.0                           ── E: 0     | W: 0     | N: 0    

✓ missCompare 1.0.1                      ── E: 0     | W: 0     | N: 0    

✓ robCompositions 2.2.1                  ── E: 0     | W: 1     | N: 0    

✓ sdcMicro 5.5.1                         ── E: 0     | W: 0     | N: 0    

✓ simPop 1.2.0                           ── E: 0     | W: 0     | N: 0    

I simputation 0.2.4                      ── E: 1     | W: 0     | N: 0   
 
✓ smartdata 1.0.3                        ── E: 2     | W: 0     | N: 1    
`

Errors seem not to be VIM related (so no change in check old/new

**Comment by GregorDeCillia** [comment]
thanks! I decided to go for a "squash and merge" because some of the commit messages expose unnecessary details for the main commit history.

**Pull request merged**
